# Generated by Django 4.0.4 on 2022-05-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hName', models.CharField(max_length=30)),
                ('sName', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('dist', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('Pin', models.CharField(max_length=30)),
            ],
        ),
    ]
