# Generated by Django 4.0.4 on 2022-05-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addperson',
            old_name='Pin',
            new_name='pin',
        ),
    ]
